[package]
name = "mining_proxy_sv2"
version = "0.1.1"
authors = ["user"]
edition = "2018"
description = "SV2 mining proxy role"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"

[lib]
name = "mining_proxy_sv2"
path = "src/lib/mod.rs"

[dependencies]
stratum-common = { version = "1.0.0", path = "../../common" }
async-channel = "1.8.0"
async-recursion = "0.3.2"
binary_sv2 = { version = "^1.0.0", path = "../../protocols/v2/binary-sv2/binary-sv2" }
buffer_sv2 = { version = "^1.0.0", path = "../../utils/buffer" }
codec_sv2 = { version = "^1.0.1", path = "../../protocols/v2/codec-sv2", features = [
  "noise_sv2",
  "with_buffer_pool",
] }
const_sv2 = { version = "^1.0.0", path = "../../protocols/v2/const-sv2" }
futures = "0.3.19"
network_helpers_sv2 = { version = "2.0.0", path = "../roles-utils/network-helpers", features = [
  "with_tokio",
  "with_buffer_pool",
] }
once_cell = "1.12.0"
roles_logic_sv2 = { version = "^1.0.0", path = "../../protocols/v2/roles-logic-sv2" }
serde = { version = "1.0.89", features = [
  "derive",
  "alloc",
], default-features = false }
tokio = { version = "1", features = ["full"] }
toml = { version = "0.5.6", git = "https://github.com/diondokter/toml-rs", default-features = false, rev = "c4161aa" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
nohash-hasher = "0.2.0"
key-utils = { version = "^1.0.0", path = "../../utils/key-utils" }
