[package]
name = "framing_sv2"
version = "5.0.1"
authors = ["The Stratum V2 Developers"]
edition = "2021"
readme = "README.md"
description = "Sv2 frames"
documentation = "https://docs.rs/framing_sv2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"
homepage = "https://stratumprotocol.org"
keywords = ["stratum", "mining", "bitcoin", "protocol"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binary_sv2 = { path = "../../../protocols/v2/binary-sv2", version = "^4.0.0" }
buffer_sv2 = { path = "../../../utils/buffer", optional=true, version = "^2.0.0" }
noise_sv2 = { path = "../../../protocols/v2/noise-sv2", version = "^1.0.0" }

[dev-dependencies]
noise_sv2 = { path = "../../../protocols/v2/noise-sv2", version = "^1.0.0" }
rand = "0.8.3"
secp256k1 = { version = "0.28.2", default-features = false, features =["alloc","rand","rand-std"] }

[features]
with_buffer_pool = ["binary_sv2/with_buffer_pool", "buffer_sv2"]

[package.metadata.docs.rs]
features = ["with_buffer_pool"]
