[package]
name = "framing_sv2"
version = "1.1.0"
authors = ["fi3 <email@email.org>"]
edition = "2018"
description = "Sv2 frames"
license = "MIT"
repository = "https://github.com/stratum-mining/stratum"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
serde = { version = "1.0.89", default-features = false, optional = true }
const_sv2 = { version = "^1.0.0", path = "../../../protocols/v2/const-sv2"}
binary_sv2 = { version = "^1.0.0", path = "../../../protocols/v2/binary-sv2/binary-sv2" }
buffer_sv2 = { version = "^1.0.0", path = "../../../utils/buffer", optional=true }

[features]
with_serde = ["binary_sv2/with_serde", "serde", "buffer_sv2/with_serde"]
with_buffer_pool = ["binary_sv2/with_buffer_pool", "buffer_sv2"]
