[package]
name = "network_helpers"
version = "0.1.0"
authors = ["fi3 <email@email.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.8.0", optional = true }
async-channel = { version = "1.5.1", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
binary_sv2 = { path = "../../protocols/v2/binary-sv2/binary-sv2", optional = true }
codec_sv2 = { path = "../../protocols/v2/codec-sv2", features=["noise_sv2"], optional = true }
serde = { version = "1.0.89", features = ["derive"], default-features = false, optional = true }
tracing = { version = "0.1" }

[features]
async_std = ["async-std", "async-channel", "binary_sv2", "codec_sv2"]
with_tokio = ["tokio", "async-channel", "binary_sv2", "codec_sv2"]
with_serde = ["binary_sv2/with_serde", "serde", "codec_sv2/with_serde"]
with_buffer_pool = ["codec_sv2/with_buffer_pool"]
