[package]
name = "mining-device"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec_sv2 = { path = "../../../../protocols/v2/codec-sv2", features=["noise_sv2"] }
roles_logic_sv2 = { path = "../../../../protocols/v2/roles-logic-sv2" }
const_sv2 = { path = "../../../../protocols/v2/const-sv2" }
async-channel = "1.5.1"
async-std={version = "1.8.0", features = ["attributes"]}
binary_sv2 = { path = "../../../../protocols/v2/binary-sv2/binary-sv2" }
network_helpers = { path = "../../../../utils/network-helpers", features=["async_std"] }
buffer_sv2 = { path = "../../../../utils/buffer"}
async-recursion = "0.3.2"
rand = "0.8.4"
bitcoin = "0.27.1"
futures = "0.3.5"
