[package]
name = "derive_codec_sv2"
version = "1.1.1"
authors = ["The Stratum V2 Developers"]
edition = "2021"
readme = "README.md"
description = "Derive macro for Sv2 binary format serializer and deserializer"
documentation = "https://docs.rs/derive_codec_sv2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"
homepage = "https://stratumprotocol.org"
keywords = ["stratum", "mining", "bitcoin", "protocol"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binary_codec_sv2 = { path="../codec", version = "^3.0.0" }

[lib]
proc-macro = true
