[package]
name = "job_declaration_sv2"
version = "5.0.1"
authors = ["The Stratum V2 Developers"]
edition = "2021"
readme = "README.md"
description = "SV2 job declaration protocol types"
documentation = "https://docs.rs/job_declaration_sv2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"
homepage = "https://stratumprotocol.org"
keywords = ["stratum", "mining", "bitcoin", "protocol"]


[dependencies]
binary_sv2 = { path = "../../binary-sv2", version = "^4.0.0" }
