[package]
name = "job_declaration_sv2"
version = "1.0.0"
authors = ["The Stratum V2 Developers"]
edition = "2018"
readme = "README.md"
description = "SV2 job declaration protocol types"
documentation = "https://docs.rs/job_declaration_sv2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"
homepage = "https://stratumprotocol.org"
keywords = ["stratum", "mining", "bitcoin", "protocol"]


[dependencies]
serde = { version = "1.0.89", default-features = false, optional= true }
binary_sv2 = {version = "^1.0.0", path = "../../binary-sv2/binary-sv2" }
const_sv2 = {version = "^2.0.0", path = "../../const-sv2"}

[features]
no_std = []
with_serde = ["binary_sv2/with_serde", "serde"]

[package.metadata.docs.rs]
all-features = true
