[package]
name = "mining_sv2"
version = "5.0.1"
authors = ["The Stratum V2 Developers"]
edition = "2021"
readme = "README.md"
description = "SV2 mining protocol types"
documentation = "https://docs.rs/mining_sv2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"
homepage = "https://stratumprotocol.org"
keywords = ["stratum", "mining", "bitcoin", "protocol"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binary_sv2 = { path = "../../binary-sv2", version = "^4.0.0" }

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1"

