[package]
name = "mining_sv2"
version = "1.0.0"
authors = ["fi3 <email@email.org>"]
edition = "2018"
description = "SV2 mining protocol types"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.89", default-features = false, optional= true }
binary_sv2 = {version = "^1.0.0", path = "../../../../protocols/v2/binary-sv2/binary-sv2" }
const_sv2 = {version = "^2.0.0", path = "../../../../protocols/v2/const-sv2"}

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1"

[features]
no_std = []
with_serde = ["binary_sv2/with_serde", "serde"]
