[package]
name = "key-utils"
version = "1.1.0"
edition = "2021"
description = "Key utils"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "key_utils"
path = "src/lib.rs"

[[bin]]
name = "key-utils-bin"
path = "src/main.rs"

[dependencies]
bs58 = { version ="0.4.0", features = ["check"] }
secp256k1 = { version = "0.28.2", default-features = false, features =["alloc","rand","rand-std"] }
serde = { version = "1.0.89", features = ["derive","alloc"], default-features = false }

[dev-dependencies]
toml = { version = "0.5.6", git = "https://github.com/diondokter/toml-rs", default-features = false, rev = "c4161aa" }
