[package]
name = "sv2_ffi"
version = "1.0.2"
authors = ["The Stratum V2 Developers"]
edition = "2018"
description = "SV2 FFI"
documentation = "https://github.com/stratum-mining/stratum"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"
homepage = "https://stratumprotocol.org"
keywords = ["stratum", "mining", "bitcoin", "protocol"]

[lib]
crate-type = ["staticlib"]

[dependencies]
codec_sv2 = { path = "../../../protocols/v2/codec-sv2" }
const_sv2 = { path = "../../../protocols/v2/const-sv2" }
binary_sv2 = { path = "../../../protocols/v2/binary-sv2/binary-sv2" }
common_messages_sv2 = { path = "../../../protocols/v2/subprotocols/common-messages" }
template_distribution_sv2 = { path = "../../../protocols/v2/subprotocols/template-distribution" }

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1"

[features]
prop_test = ["binary_sv2/prop_test", "common_messages_sv2/prop_test", "template_distribution_sv2/prop_test"]
