[package]
name = "handlers_sv2"
version = "0.1.0"
authors = ["The Stratum V2 Developers"]
edition = "2021"
description = "Sv2 Message handlers"
documentation = "https://docs.rs/handlers_sv2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"
homepage = "https://stratumprotocol.org"
keywords = ["stratum", "mining", "bitcoin", "protocol"]

[dependencies]
trait-variant = "0.1.2"
parsers_sv2 = { path = "../parsers-sv2", version = "^0.1.0"}
binary_sv2 = { path = "../binary-sv2", version = "^4.0.0" }
common_messages_sv2 = { path = "../subprotocols/common-messages", version = "^6.0.0" }
mining_sv2 = { path = "../subprotocols/mining", version = "^5.0.0" }
template_distribution_sv2 = { path = "../subprotocols/template-distribution", version = "^4.0.0" }
job_declaration_sv2 = { path = "../subprotocols/job-declaration", version = "^5.0.0" }
