[package]
name = "template_distribution_sv2"
version = "1.0.2"
authors = ["The Stratum V2 Developers"]
edition = "2018"
readme = "README.md"
description = "Sv2 template distribution subprotocol"
documentation = "https://docs.rs/template_distribution_sv2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"
homepage = "https://stratumprotocol.org"
keywords = ["stratum", "mining", "bitcoin", "protocol"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.89", default-features = false, optional= true }
binary_sv2 = { version = "^1.0.1", path = "../../binary-sv2/binary-sv2" }
const_sv2 = { version = "^2.0.0", path = "../../const-sv2"}
quickcheck = { version = "1.0.3", optional=true }
quickcheck_macros = { version = "1", optional=true }

[features]
no_std = []
with_serde = ["binary_sv2/with_serde", "serde"]
prop_test = ["quickcheck"]

[package.metadata.docs.rs]
all-features = true