[package]
name = "buffer_sv2"
version = "1.0.0"
authors = ["fi3 <email@email.org>"]
edition = "2018"
description = "buffer"
license = "MIT"
repository = "https://github.com/stratum-mining/stratum"

[dependencies]
criterion = {version = "0.3", optional = true}
serde = { version = "1.0.89", features = ["derive", "alloc"], default-features = false, optional = true }
aes-gcm = "0.10.2"

[dev-dependencies]
rand = "0.8.3"
iai = "0.1"


[[bench]]
name = "pool_benchmark"
harness = false

[[bench]]
name = "pool_iai"
harness = false

[features]
debug = []
fuzz = []
with_serde = ["serde"]
