[package]
name = "extensions_sv2"
version = "0.1.1"
authors = ["The Stratum V2 Developers"]
edition = "2021"
readme = "README.md"
description = "Sv2 Extension Messages"
documentation = "https://docs.rs/extensions_sv2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"
homepage = "https://stratumprotocol.org"
keywords = ["stratum", "mining", "bitcoin", "protocol", "extensions"]

[dependencies]
binary_sv2 = { path = "../binary-sv2", version = "^6.0.0" }
