[package]
name = "framing_sv2"
version = "6.0.1"
authors = ["The Stratum V2 Developers"]
edition = "2021"
readme = "README.md"
description = "Sv2 frames"
documentation = "https://docs.rs/framing_sv2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"
homepage = "https://stratumprotocol.org"
keywords = ["stratum", "mining", "bitcoin", "protocol"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binary_sv2 = { path = "../binary-sv2", version = "^5.0.0" }
buffer_sv2 = { path = "../buffer-sv2", optional=true, version = "^3.0.0" }
noise_sv2 = { path = "../noise-sv2", version = "^1.0.0" }

[dev-dependencies]
criterion = { workspace = true, features = ["html_reports"] }
rand = { workspace = true, default-features = true }
secp256k1 = { workspace = true, features = ["alloc", "rand", "rand-std"] }
rayon-core = { workspace = true }

[features]
with_buffer_pool = ["binary_sv2/with_buffer_pool", "buffer_sv2"]

[package.metadata.docs.rs]
features = ["with_buffer_pool"]


[[bench]]
name = "framing"
harness = false
