name: Protocol test Coverage

on:
  push:
    branches:
      - main

jobs:
  protocols-coverage:

    name: tarpaulin Test
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:0.27.1-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate code coverage
        run: |
          ./scripts/coverage-protocols.sh

      - name: Upload protocols coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./protocols/target/tarpaulin-reports
          file: ./protocols/target/tarpaulin-reports/cobertura.xml
          flags: protocols
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload binary_codec_sv2-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./protocols/target/tarpaulin-reports/codec-coverage
          file: ./protocols/target/tarpaulin-reports/codec-coverage/cobertura.xml
          flags: binary_codec_sv2-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Upload binary_sv2-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./protocols/target/tarpaulin-reports/binary-sv2-coverage
          file: ./protocols/target/tarpaulin-reports/binary-sv2-coverage/cobertura.xml
          flags: binary_sv2-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload codec_sv2-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./protocols/target/tarpaulin-reports/codec-sv2-coverage
          file: ./protocols/target/tarpaulin-reports/codec-sv2-coverage/cobertura.xml
          flags: codec_sv2-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload channels_sv2-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./protocols/target/tarpaulin-reports/channels-sv2-coverage
          file: ./protocols/target/tarpaulin-reports/channels-sv2-coverage/cobertura.xml
          flags: channels_sv2-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload common_messages_sv2-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./protocols/target/tarpaulin-reports/common-messages-coverage
          file: ./protocols/target/tarpaulin-reports/common-messages-coverage/cobertura.xml
          flags: common_messages_sv2-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload framing_sv2-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./protocols/target/tarpaulin-reports/framing-sv2-coverage
          file: ./protocols/target/tarpaulin-reports/framing-sv2-coverage/cobertura.xml
          flags: framing_sv2-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload job_declaration_sv2-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./protocols/target/tarpaulin-reports/job-declaration-coverage
          file: ./protocols/target/tarpaulin-reports/job-declaration-coverage/cobertura.xml
          flags: job_declaration_sv2-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload noise_sv2-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./protocols/target/tarpaulin-reports/noise-sv2-coverage
          file: ./protocols/target/tarpaulin-reports/noise-sv2-coverage/cobertura.xml
          flags: noise_sv2-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload roles_logic_sv2-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./protocols/target/tarpaulin-reports/roles-logic-sv2-coverage
          file: ./protocols/target/tarpaulin-reports/roles-logic-sv2-coverage/cobertura.xml
          flags: roles_logic_sv2-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload v1-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./protocols/target/tarpaulin-reports/v1-coverage
          file: ./protocols/target/tarpaulin-reports/v1-coverage/cobertura.xml
          flags: v1-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload sv2_ffi-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./protocols/target/tarpaulin-reports/sv2-ffi-coverage
          file: ./protocols/target/tarpaulin-reports/sv2-ffi-coverage/cobertura.xml
          flags: sv2_ffi-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload template_distribution_sv2-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./protocols/target/tarpaulin-reports/template-distribution-coverage
          file: ./protocols/target/tarpaulin-reports/template-distribution-coverage/cobertura.xml
          flags: template_distribution_sv2-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload mining-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./protocols/target/tarpaulin-reports/mining-coverage
          file: ./protocols/target/tarpaulin-reports/mining-coverage/cobertura.xml
          flags: mining-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
