name: Run and Cache Benchmarks

on: 
  pull_request:
    branches:
      - main
      - dev

jobs:
  benchmark_sv1_criterion:
    name: Run and cache criterion sv1 benchmarks 
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.75.0
          override: true

      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Run Benchmarks
        run: |
          cd benches 
          cargo bench --bench criterion_sv1_benchmark > criterion_sv1_benchmarks.txt

      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: criterion_sv1_benchmarks.txt
          path: ./benches/criterion_sv1_benchmarks.txt
      

  benchmark_sv2_criterion:
    name: Run and cache criterion sv2 benchmarks 
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.75.0
          override: true

      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Run Benchmarks
        run: |
          cd benches 
          cargo bench --bench criterion_sv2_benchmark > criterion_sv2_benchmarks.txt
      
      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: criterion_sv2_benchmarks.txt
          path: ./benches/criterion_sv2_benchmarks.txt

  benchmark_sv1_iai:
    name: Run and cache iai sv1 benchmarks 
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.75.0
          override: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind=1:3.18.1-1ubuntu2 
          
      - name: Run Benchmarks
        run: |
          cd benches 
          cargo bench --bench iai_sv1_benchmark > iai_sv1_benchmarks.txt
      
      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: iai_sv1_benchmarks.txt
          path: ./benches/iai_sv1_benchmarks.txt
  
  benchmark_sv2_iai:
    name: Run and cache iai sv2 benchmarks 
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.75.0
          override: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind=1:3.18.1-1ubuntu2 
          
      - name: Run Benchmarks
        run: |
          cd benches 
          cargo bench --bench iai_sv2_benchmark > iai_sv2_benchmarks.txt
      
      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: iai_sv2_benchmarks.txt
          path: ./benches/iai_sv2_benchmarks.txt

      - name: Upload GitHub Pull Request Event
        uses: actions/upload-artifact@v4
        with:
          name: event.json
          path: ${{ github.event_path }}
